[mcp_servers.brainsync]
args = ['c:\Users\hudav\.antigravity\extensions\dawoodahmad.brainsync-3.0.12-universal\dist\mcp-server.js']
command = "node"

[mcp_servers.brainsync.env]
BRAINSYNC_ENV_FILE = 'C:\Users\hudav\.bsync_core\webapp\mcp-secret-env.json'
