export const lokSabhaToVidhanSabha: Record<string, string[]> = {
  "Chandni Chowk": ["Adarsh Nagar", "Shalimar Bagh", "Shakur Basti", "Tri Nagar", "Wazirpur", "Model Town", "Sadar Bazar", "Chandni Chowk", "Matia Mahal", "Ballimaran"],
  "North East Delhi": ["Burari", "Timarpur", "Seemapuri", "Rohtas Nagar", "Seelampur", "Ghonda", "Babarpur", "Gokalpur", "Mustafabad", "Karawal Nagar"],
  "East Delhi": ["Jangpura", "Okhla", "Trilokpuri", "Kondli", "Patparganj", "Laxmi Nagar", "Vishwas Nagar", "Krishna Nagar", "Gandhi Nagar", "Shahdara"],
  "New Delhi": ["Karol Bagh", "Patel Nagar", "Moti Nagar", "Delhi Cantonment", "Rajinder Nagar", "New Delhi", "Kasturba Nagar", "Malviya Nagar", "R.K. Puram", "Greater Kailash"],
  "North West Delhi": ["Narela", "Badli", "Rithala", "Bawana", "Mundka", "Kirari", "Sultanpur Majra", "Nangloi Jat", "Mangol Puri", "Rohini"],
  "West Delhi": ["Madipur", "Rajouri Garden", "Hari Nagar", "Tilak Nagar", "Janakpuri", "Vikaspuri", "Uttam Nagar", "Dwarka", "Matiala", "Najafgarh"],
  "South Delhi": ["Bijwasan", "Palam", "Mehrauli", "Chhatarpur", "Deoli", "Ambedkar Nagar", "Sangam Vihar", "Kalkaji", "Tughlakabad", "Badarpur"]
};

export const delhiConstituenciesAndWards: Record<string, string[]> = {
  "Narela": ["Narela (W)", "Bankner", "Holambi Kalan (W)", "Alipur", "Bakhtawarpur (W)"],
  "Burari": ["Burari", "Kadipur (W)", "Mukundpur", "Sant Nagar (W)", "Jharoda"],
  "Timarpur": ["Timarpur (W)", "Malka Ganj (SC-W)", "Mukherjee Nagar", "Dhirpur (W)"],
  "Adarsh Nagar": ["Adarsh Nagar", "Azadpur (W)", "Bhalswa", "Jahangir Puri (W)", "Sarup Nagar"],
  "Badli": ["Samaypur Badli (W)", "Rohini-A", "Rohini-B (W)"],
  "Rithala": ["Rithala", "Vijay Vihar (W)", "Budh Vihar", "Pooth Kalan (W)"],
  "Bawana": ["Begumpur", "Shahbaad Dairy (SC)", "Pooth Khurd (W)", "Bawana", "Nangal Thakran (W)"],
  "Mundka": ["Kanjhawala", "Rani Khera (W)", "Nangloi (SC-W)", "Mundka", "Nilothi (W)"],
  "Kirari": ["Kirari", "Prem Nagar (W)", "Mubarikpur", "Nithari (W)", "Aman Vihar"],
  "Sultanpur Majra": ["Mangol Puri (SC)", "Sultanpuri-A (SC-W)", "Sultanpuri-B (SC)"],
  "Nangloi Jat": ["Jawalapuri (SC-W)", "Nangloi Jat (W)", "Nihal Vihar", "Guru Harkishan Nagar (W)"],
  "Mangol Puri": ["Mangolpuri-A (SC)", "Mangolpuri-B (SC-W)", "Rohini-C"],
  "Rohini": ["Rohini-F (W)", "Rohini-E", "Rohini-D (W)"],
  "Shalimar Bagh": ["Shalimar Bagh-A", "Shalimar Bagh-B (W)", "Pitam Pura", "Saraswati Vihar (W)"],
  "Shakur Basti": ["Paschim Vihar", "Rani Bagh (W)", "Kohat Enclave"],
  "Tri Nagar": ["Shakur Pur (SC)", "Tri Nagar (W)", "Keshav Puram"],
  "Wazirpur": ["Ashok Vihar (W)", "Wazir Pur (SC-W)", "Sangam Park (SC)"],
  "Model Town": ["Model Town", "Kamla Nagar (W)", "Shastri Nagar"],
  "Sadar Bazar": ["Kishan Ganj (SC-W)", "Sadar Bazar (W)", "Civil Lines (SC)"],
  "Chandni Chowk": ["Chandni Chowk", "Jama Masjid (W)", "Chandani Mahal"],
  "Matia Mahal": ["Delhi Gate (SC-W)", "Bazar Sita Ram (W)", "Ballimaran"],
  "Ballimaran": ["Ram Nagar (SC)", "Quraish Nagar (W)", "Pahar Ganj"],
  "Karol Bagh": ["Karol Bagh (SC-W)", "Dev Nagar (SC)", "West Patel Nagar (SC-W)"],
  "Patel Nagar": ["East Patel Nagar (W)", "Ranjeet Nagar", "Baljeet Nagar (W)", "Karam Pura"],
  "Moti Nagar": ["Moti Nagar (W)", "Ramesh Nagar", "Punjabi Bagh (W)"],
  "Madipur": ["Madipur (SC)", "Raghubir Nagar (SC-W)", "Vishnu Garden"],
  "Rajouri Garden": ["Rajouri Garden (W)", "Chaukhandi Nagar", "Subhash Nagar (W)"],
  "Hari Nagar": ["Hari Nagar", "Fateh Nagar (W)", "Tilak Nagar", "Khyala (W)"],
  "Tilak Nagar": ["Keshopur", "Janak Puri South (W)", "Mahaveer Enclave"],
  "Janakpuri": ["Janak Puri West (W)", "Vikas Puri", "Hastsal (W)"],
  "Vikaspuri": ["Shiv Vihar", "Bhakkar Wala (W)", "Baprola", "Vikas Nagar (W)", "Mohan Garden-West", "Mohan Garden-East (W)"],
  "Uttam Nagar": ["Uttam Nagar", "Binda Pur (W)", "Dabri"],
  "Dwarka": ["Sagarpur (W)", "Manglapuri", "Dwarka-B (W)"],
  "Matiala": ["Dwarka-A", "Matiala (W)", "Kakrola", "Nangli Sakrawati (W)", "Chhawala", "Isapur (W)"],
  "Najafgarh": ["Najafgarh", "Dichaon Kalan (W)", "Roshan Pura"],
  "Bijwasan": ["Dwarka-C (W)", "Bijwasan", "Kapashera (W)"],
  "Palam": ["Mahipalpur", "Raj Nagar (W)", "Palam", "Madhu Vihar (W)"],
  "Rajinder Nagar": ["Mahavir Enclave", "Sadh Nagar (W)", "Naraina"],
  "Jangpura": ["Inder Puri (SC)", "Rajinder Nagar (W)", "Daryaganj"],
  "Kasturba Nagar": ["Sidhartha Nagar (W)", "Lajpat Nagar", "Andrews Ganj (W)"],
  "Malviya Nagar": ["Amar Colony", "Kotla Mubarakpur (W)", "Hauz Khas"],
  "R.K. Puram": ["Malviya Nagar (W)", "Green Park", "Munirka (W)"],
  "Mehrauli": ["R.K Puram", "Vasant Vihar (W)", "Lado Sarai"],
  "Chhatarpur": ["Mehrauli (W)", "Vasant Kunj", "Aya Nagar (W)"],
  "Deoli": ["Bhati", "Chhatarpur (W)", "Said-Ul-Ajaib", "Deoli (W)"],
  "Ambedkar Nagar": ["Tigri (SC-W)", "Sangam Vihar-A", "Dakshin Puri (SC)"],
  "Sangam Vihar": ["Madangir (SC-W)", "Pushp Vihar (SC)", "Khanpur (W)", "Sangam Vihar-C"],
  "Greater Kailash": ["Sangam Vihar-B (W)", "Tughlakabad Extension", "Chitaranjan Park (W)"],
  "Kalkaji": ["Chirag Delhi", "Greater Kailash (W)", "Sri Niwas Puri"],
  "Tughlakabad": ["Kalkaji (W)", "Govind Puri", "Harkesh Nagar (SC-W)", "Tughlakabad (W)"],
  "Badarpur": ["Pul Pehladpur (SC)", "Badarpur (SC-W)", "Molarband", "Meethapur (W)", "Hari Nagar Extension"],
  "Okhla": ["Jaitpur (W)", "Madanpur Khadar East (SC)", "Madanpur Khadar West", "Sarita Vihar (W)", "Abul Fazal Enclave"],
  "Trilokpuri": ["Zakir Nagar (W)", "New Ashok Nagar", "Mayur Vihar Phase-I (SC-W)"],
  "Kondli": ["Trilokpuri (SC)", "Kondli (W)", "Gharoli (SC-W)"],
  "Patparganj": ["Kalyanpuri (SC)", "Mayur Vihar Phase-II", "Patpar Ganj (SC)", "Vinod Nagar"],
  "Laxmi Nagar": ["Mandawali (SC)", "Pandav Nagar", "Lalita Park (W)", "Shakarpur"],
  "Vishwas Nagar": ["Laxmi Nagar (SC)", "Preet Vihar", "I.P Extension (SC)", "Anand Vihar"],
  "Krishna Nagar": ["Vishwas Nagar (SC-W)", "Anarkali (W)", "Jagat Puri", "Geeta Colony (W)"],
  "Gandhi Nagar": ["Krishna Nagar", "Gandhi Nagar (W)", "Shastri Park", "Azad Nagar (W)"],
  "Shahdara": ["Shahdara (SC)", "Jhilmil", "Dilshad Colony (W)", "Sundar Nagri (SC-W)"],
  "Seemapuri": ["Dilshad Garden", "Nand Nagri (SC)", "Ashok Nagar (W)", "Ram Nagar East"],
  "Rohtas Nagar": ["Rohtash Nagar (W)", "Welcome Colony", "Seelampur (W)", "Gautam Puri"],
  "Seelampur": ["Chauhan Banger (W)", "Maujpur", "Braham Puri (W)", "Bhajanpura"],
  "Ghonda": ["Ghonda (W)", "Yamuna Vihar", "Subash Mohalla (W)", "Kabir Nagar", "Gorakh Park (W)"],
  "Babarpur": ["Kardam Puri", "Harsh Vihar (SC-W)", "Saboli (SC)"],
  "Gokalpur": ["Gokal Puri (SC-W)", "Joharipur (SC)", "Karawal Nagar-East (W)", "Dayalpur"],
  "Mustafabad": ["Mustafabad (W)", "Nehru Vihar", "Brij Puri (W)", "Sri Ram Colony", "Sadatpur (W)"],
  "Karawal Nagar": ["Karawal Nagar-West", "Sonia Vihar (W)", "Sabapur"],
  "New Delhi": ["NDMC Area"],
  "Delhi Cantonment": ["Cantonment Board Area"]
};

export const allWardsList = Object.values(delhiConstituenciesAndWards).flat();
