-- Migration 13: Delhi Post-2022 Delimitation Wards & Assembly Constituencies
-- Based on the Delimitation Order (October 17, 2022) by the Ministry of Home Affairs / State Election Commission
-- 70 Assembly Constituencies and 250 Municipal Corporation of Delhi (MCD) Wards

CREATE TABLE IF NOT EXISTS public.assembly_constituencies (
    ac_number INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    lok_sabha TEXT NOT NULL,
    district TEXT NOT NULL,
    ward_count INTEGER NOT NULL,
    zone TEXT NOT NULL,
    is_reserved_sc BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.mcd_wards (
    ward_number INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    raw_name TEXT NOT NULL,
    ac_number INTEGER NOT NULL REFERENCES public.assembly_constituencies(ac_number) ON DELETE CASCADE,
    ac_name TEXT NOT NULL,
    lok_sabha TEXT NOT NULL,
    district TEXT NOT NULL,
    zone TEXT NOT NULL,
    reservation TEXT NOT NULL CHECK (reservation IN ('GEN', 'WOMEN', 'SC', 'SC_WOMEN')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mcd_wards_ac_number ON public.mcd_wards(ac_number);
CREATE INDEX IF NOT EXISTS idx_mcd_wards_zone ON public.mcd_wards(zone);
CREATE INDEX IF NOT EXISTS idx_mcd_wards_reservation ON public.mcd_wards(reservation);

ALTER TABLE public.assembly_constituencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcd_wards ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'assembly_constituencies' AND policyname = 'Allow public read access to assembly constituencies'
    ) THEN
        CREATE POLICY "Allow public read access to assembly constituencies"
            ON public.assembly_constituencies FOR SELECT TO anon, authenticated USING (true);
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'mcd_wards' AND policyname = 'Allow public read access to mcd wards'
    ) THEN
        CREATE POLICY "Allow public read access to mcd wards"
            ON public.mcd_wards FOR SELECT TO anon, authenticated USING (true);
    END IF;
END $$;

GRANT SELECT ON public.assembly_constituencies TO anon, authenticated;
GRANT SELECT ON public.mcd_wards TO anon, authenticated;

INSERT INTO public.assembly_constituencies (ac_number, name, lok_sabha, district, ward_count, zone, is_reserved_sc)
VALUES
(1, 'Narela', 'North West Delhi', 'North', 5, 'Narela', false),
(2, 'Burari', 'North East Delhi', 'Central', 5, 'Civil Lines', false),
(3, 'Timarpur', 'North East Delhi', 'Central', 3, 'Civil Lines', false),
(4, 'Adarsh Nagar', 'Chandni Chowk', 'North', 3, 'Civil Lines', false),
(5, 'Badli', 'North West Delhi', 'North', 4, 'Civil Lines', false),
(6, 'Rithala', 'North West Delhi', 'North West', 5, 'Rohini', false),
(7, 'Bawana', 'North West Delhi', 'North', 6, 'Narela', true),
(8, 'Mundka', 'North West Delhi', 'West', 5, 'Narela', false),
(9, 'Kirari', 'North West Delhi', 'North West', 5, 'Rohini', false),
(10, 'Sultan Pur Majra', 'North West Delhi', 'North West', 3, 'Rohini', true),
(11, 'Nangloi Jat', 'North West Delhi', 'West', 4, 'West', false),
(12, 'Mangol Puri', 'North West Delhi', 'North West', 3, 'Rohini', true),
(13, 'Rohini', 'North West Delhi', 'North West', 3, 'Rohini', false),
(14, 'Shalimar Bagh', 'Chandni Chowk', 'North West', 3, 'Keshav Puram', false),
(15, 'Shakur Basti', 'Chandni Chowk', 'North', 4, 'Keshav Puram', false),
(16, 'Tri Nagar', 'Chandni Chowk', 'North', 3, 'Keshav Puram', false),
(17, 'Wazirpur', 'Chandni Chowk', 'North', 2, 'Keshav Puram', false),
(18, 'Model Town', 'Chandni Chowk', 'North', 3, 'Civil Lines', false),
(19, 'Sadar Bazar', 'Chandni Chowk', 'Central', 4, 'City SP', false),
(20, 'Chandni Chowk', 'Chandni Chowk', 'Central', 3, 'City SP', false),
(21, 'Matia Mahal', 'Chandni Chowk', 'Central', 2, 'City SP', false),
(22, 'Ballimaran', 'Chandni Chowk', 'Central', 3, 'City SP', false),
(23, 'Karol Bagh', 'New Delhi', 'Central', 3, 'Karol Bagh', true),
(24, 'Patel Nagar', 'New Delhi', 'Central', 4, 'Karol Bagh', true),
(25, 'Moti Nagar', 'New Delhi', 'West', 4, 'Karol Bagh', false),
(26, 'Madipur', 'West Delhi', 'West', 3, 'West', true),
(27, 'Rajouri Garden', 'West Delhi', 'West', 3, 'West', false),
(28, 'Hari Nagar', 'West Delhi', 'West', 4, 'West', false),
(29, 'Tilak Nagar', 'West Delhi', 'West', 3, 'West', false),
(30, 'Janakpuri', 'West Delhi', 'West', 3, 'West', false),
(31, 'Vikas Puri', 'West Delhi', 'West', 6, 'West', false),
(32, 'Uttam Nagar', 'West Delhi', 'South West', 3, 'Najafgarh', false),
(33, 'Dwarka', 'West Delhi', 'South West', 3, 'Najafgarh', false),
(34, 'Matiala', 'West Delhi', 'South West', 4, 'Najafgarh', false),
(35, 'Najafgarh', 'West Delhi', 'South West', 5, 'Najafgarh', false),
(36, 'Bijwasan', 'South Delhi', 'South West', 4, 'Najafgarh', false),
(37, 'Palam', 'South Delhi', 'South West', 5, 'Najafgarh', false),
(38, 'Delhi Cantonment', 'New Delhi', 'New Delhi', 0, 'Cantonment Board', false),
(39, 'Rajinder Nagar', 'New Delhi', 'New Delhi', 3, 'Karol Bagh', false),
(40, 'New Delhi', 'New Delhi', 'New Delhi', 0, 'NDMC', false),
(41, 'Jangpura', 'East Delhi', 'South East', 3, 'Central', false),
(42, 'Kasturba Nagar', 'New Delhi', 'South', 3, 'Central', false),
(43, 'Malviya Nagar', 'New Delhi', 'South', 3, 'South', false),
(44, 'R.K. Puram', 'New Delhi', 'New Delhi', 3, 'South', false),
(45, 'Mehrauli', 'South Delhi', 'South', 3, 'South', false),
(46, 'Chhatarpur', 'South Delhi', 'South', 3, 'South', false),
(47, 'Deoli', 'South Delhi', 'South', 4, 'South', true),
(48, 'Ambedkar Nagar', 'South Delhi', 'South', 3, 'South', true),
(49, 'Sangam Vihar', 'South Delhi', 'South', 3, 'South', false),
(50, 'Greater Kailash', 'New Delhi', 'South', 4, 'Central', false),
(51, 'Kalkaji', 'South Delhi', 'South East', 3, 'Central', false),
(52, 'Tughlakabad', 'South Delhi', 'South East', 2, 'Central', false),
(53, 'Badarpur', 'South Delhi', 'South East', 5, 'Central', false),
(54, 'Okhla', 'East Delhi', 'South East', 6, 'Central', false),
(55, 'Trilokpuri', 'East Delhi', 'East', 3, 'Shahdara South', true),
(56, 'Kondli', 'East Delhi', 'East', 3, 'Shahdara South', true),
(57, 'Patparganj', 'East Delhi', 'East', 4, 'Shahdara South', false),
(58, 'Laxmi Nagar', 'East Delhi', 'East', 4, 'Shahdara South', false),
(59, 'Vishwas Nagar', 'East Delhi', 'Shahdara', 4, 'Shahdara South', false),
(60, 'Krishna Nagar', 'East Delhi', 'East', 4, 'Shahdara South', false),
(61, 'Gandhi Nagar', 'East Delhi', 'East', 3, 'Shahdara South', false),
(62, 'Shahdara', 'East Delhi', 'Shahdara', 3, 'Shahdara North', false),
(63, 'Seemapuri', 'North East Delhi', 'Shahdara', 4, 'Shahdara North', true),
(64, 'Rohtas Nagar', 'North East Delhi', 'Shahdara', 3, 'Shahdara North', false),
(65, 'Seelampur', 'North East Delhi', 'North East', 4, 'Shahdara North', false),
(66, 'Ghonda', 'North East Delhi', 'North East', 4, 'Shahdara North', false),
(67, 'Babarpur', 'North East Delhi', 'Shahdara', 4, 'Shahdara North', false),
(68, 'Gokalpur', 'North East Delhi', 'North East', 4, 'Shahdara North', true),
(69, 'Mustafabad', 'North East Delhi', 'North East', 5, 'Shahdara North', false),
(70, 'Karawal Nagar', 'North East Delhi', 'North East', 5, 'Shahdara North', false)
ON CONFLICT (ac_number) DO UPDATE SET
    name = EXCLUDED.name,
    lok_sabha = EXCLUDED.lok_sabha,
    district = EXCLUDED.district,
    ward_count = EXCLUDED.ward_count,
    zone = EXCLUDED.zone,
    is_reserved_sc = EXCLUDED.is_reserved_sc;

INSERT INTO public.mcd_wards (ward_number, name, raw_name, ac_number, ac_name, lok_sabha, district, zone, reservation)
VALUES
(1, 'Narela', 'Narela (W)', 1, 'Narela', 'North West Delhi', 'North', 'Narela', 'WOMEN'),
(2, 'Bankner', 'Bankner', 1, 'Narela', 'North West Delhi', 'North', 'Narela', 'GEN'),
(3, 'Holambi Kalan', 'Holambi Kalan (W)', 1, 'Narela', 'North West Delhi', 'North', 'Narela', 'WOMEN'),
(4, 'Alipur', 'Alipur', 1, 'Narela', 'North West Delhi', 'North', 'Narela', 'GEN'),
(5, 'Bakhtawarpur', 'Bakhtawarpur (W)', 1, 'Narela', 'North West Delhi', 'North', 'Narela', 'WOMEN'),
(6, 'Burari', 'Burari', 2, 'Burari', 'North East Delhi', 'Central', 'Civil Lines', 'GEN'),
(7, 'Kadipur', 'Kadipur (W)', 2, 'Burari', 'North East Delhi', 'Central', 'Civil Lines', 'WOMEN'),
(8, 'Mukundpur', 'Mukundpur', 2, 'Burari', 'North East Delhi', 'Central', 'Civil Lines', 'GEN'),
(9, 'Sant Nagar', 'Sant Nagar (W)', 2, 'Burari', 'North East Delhi', 'Central', 'Civil Lines', 'WOMEN'),
(10, 'Jharoda', 'Jharoda', 2, 'Burari', 'North East Delhi', 'Central', 'Civil Lines', 'GEN'),
(11, 'Timarpur', 'Timarpur (W)', 3, 'Timarpur', 'North East Delhi', 'Central', 'Civil Lines', 'WOMEN'),
(12, 'Malka Ganj', 'Malka Ganj (SC-W)', 3, 'Timarpur', 'North East Delhi', 'Central', 'Civil Lines', 'SC_WOMEN'),
(13, 'Mukherjee Nagar', 'Mukherjee Nagar', 3, 'Timarpur', 'North East Delhi', 'Central', 'Civil Lines', 'GEN'),
(14, 'Dhirpur', 'Dhirpur (W)', 4, 'Adarsh Nagar', 'Chandni Chowk', 'North', 'Civil Lines', 'WOMEN'),
(15, 'Adarsh Nagar', 'Adarsh Nagar', 4, 'Adarsh Nagar', 'Chandni Chowk', 'North', 'Civil Lines', 'GEN'),
(16, 'Azadpur', 'Azadpur (W)', 4, 'Adarsh Nagar', 'Chandni Chowk', 'North', 'Civil Lines', 'WOMEN'),
(17, 'Bhalswa', 'Bhalswa', 5, 'Badli', 'North West Delhi', 'North', 'Civil Lines', 'GEN'),
(18, 'Jahangir Puri', 'Jahangir Puri (W)', 5, 'Badli', 'North West Delhi', 'North', 'Civil Lines', 'WOMEN'),
(19, 'Sarup Nagar', 'Sarup Nagar', 5, 'Badli', 'North West Delhi', 'North', 'Civil Lines', 'GEN'),
(20, 'Samaypur Badli', 'Samaypur Badli (W)', 5, 'Badli', 'North West Delhi', 'North', 'Civil Lines', 'WOMEN'),
(21, 'Rohini-A', 'Rohini-A', 6, 'Rithala', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(22, 'Rohini-B', 'Rohini-B (W)', 6, 'Rithala', 'North West Delhi', 'North West', 'Rohini', 'WOMEN'),
(23, 'Rithala', 'Rithala', 6, 'Rithala', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(24, 'Vijay Vihar', 'Vijay Vihar (W)', 6, 'Rithala', 'North West Delhi', 'North West', 'Rohini', 'WOMEN'),
(25, 'Budh Vihar', 'Budh Vihar', 6, 'Rithala', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(26, 'Pooth Kalan', 'Pooth Kalan (W)', 7, 'Bawana', 'North West Delhi', 'North', 'Narela', 'WOMEN'),
(27, 'Begumpur', 'Begumpur', 7, 'Bawana', 'North West Delhi', 'North', 'Narela', 'GEN'),
(28, 'Shahbaad Dairy', 'Shahbaad Dairy (SC)', 7, 'Bawana', 'North West Delhi', 'North', 'Narela', 'SC'),
(29, 'Pooth Khurd', 'Pooth Khurd (W)', 7, 'Bawana', 'North West Delhi', 'North', 'Narela', 'WOMEN'),
(30, 'Bawana', 'Bawana', 7, 'Bawana', 'North West Delhi', 'North', 'Narela', 'GEN'),
(31, 'Nangal Thakran', 'Nangal Thakran (W)', 7, 'Bawana', 'North West Delhi', 'North', 'Narela', 'WOMEN'),
(32, 'Kanjhawala', 'Kanjhawala', 8, 'Mundka', 'North West Delhi', 'West', 'Narela', 'GEN'),
(33, 'Rani Khera', 'Rani Khera (W)', 8, 'Mundka', 'North West Delhi', 'West', 'Narela', 'WOMEN'),
(34, 'Nangloi', 'Nangloi (SC-W)', 8, 'Mundka', 'North West Delhi', 'West', 'Narela', 'SC_WOMEN'),
(35, 'Mundka', 'Mundka', 8, 'Mundka', 'North West Delhi', 'West', 'Narela', 'GEN'),
(36, 'Nilothi', 'Nilothi (W)', 8, 'Mundka', 'North West Delhi', 'West', 'Narela', 'WOMEN'),
(37, 'Kirari', 'Kirari', 9, 'Kirari', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(38, 'Prem Nagar', 'Prem Nagar (W)', 9, 'Kirari', 'North West Delhi', 'North West', 'Rohini', 'WOMEN'),
(39, 'Mubarikpur', 'Mubarikpur', 9, 'Kirari', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(40, 'Nithari', 'Nithari (W)', 9, 'Kirari', 'North West Delhi', 'North West', 'Rohini', 'WOMEN'),
(41, 'Aman Vihar', 'Aman Vihar', 9, 'Kirari', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(42, 'Mangol Puri', 'Mangol Puri (SC)', 10, 'Sultan Pur Majra', 'North West Delhi', 'North West', 'Rohini', 'SC'),
(43, 'Sultanpuri-A', 'Sultanpuri-A (SC-W)', 10, 'Sultan Pur Majra', 'North West Delhi', 'North West', 'Rohini', 'SC_WOMEN'),
(44, 'Sultanpuri-B', 'Sultanpuri-B (SC)', 10, 'Sultan Pur Majra', 'North West Delhi', 'North West', 'Rohini', 'SC'),
(45, 'Jawalapuri', 'Jawalapuri (SC-W)', 11, 'Nangloi Jat', 'North West Delhi', 'West', 'West', 'SC_WOMEN'),
(46, 'Nangloi Jat', 'Nangloi Jat (W)', 11, 'Nangloi Jat', 'North West Delhi', 'West', 'West', 'WOMEN'),
(47, 'Nihal Vihar', 'Nihal Vihar', 11, 'Nangloi Jat', 'North West Delhi', 'West', 'West', 'GEN'),
(48, 'Guru Harkishan Nagar', 'Guru Harkishan Nagar (W)', 11, 'Nangloi Jat', 'North West Delhi', 'West', 'West', 'WOMEN'),
(49, 'Mangolpuri-A', 'Mangolpuri-A (SC)', 12, 'Mangol Puri', 'North West Delhi', 'North West', 'Rohini', 'SC'),
(50, 'Mangolpuri-B', 'Mangolpuri-B (SC-W)', 12, 'Mangol Puri', 'North West Delhi', 'North West', 'Rohini', 'SC_WOMEN'),
(51, 'Rohini-C', 'Rohini-C', 12, 'Mangol Puri', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(52, 'Rohini-F', 'Rohini-F (W)', 13, 'Rohini', 'North West Delhi', 'North West', 'Rohini', 'WOMEN'),
(53, 'Rohini-E', 'Rohini-E', 13, 'Rohini', 'North West Delhi', 'North West', 'Rohini', 'GEN'),
(54, 'Rohini-D', 'Rohini-D (W)', 13, 'Rohini', 'North West Delhi', 'North West', 'Rohini', 'WOMEN'),
(55, 'Shalimar Bagh-A', 'Shalimar Bagh-A', 14, 'Shalimar Bagh', 'Chandni Chowk', 'North West', 'Keshav Puram', 'GEN'),
(56, 'Shalimar Bagh-B', 'Shalimar Bagh-B (W)', 14, 'Shalimar Bagh', 'Chandni Chowk', 'North West', 'Keshav Puram', 'WOMEN'),
(57, 'Pitam Pura', 'Pitam Pura', 14, 'Shalimar Bagh', 'Chandni Chowk', 'North West', 'Keshav Puram', 'GEN'),
(58, 'Saraswati Vihar', 'Saraswati Vihar (W)', 15, 'Shakur Basti', 'Chandni Chowk', 'North', 'Keshav Puram', 'WOMEN'),
(59, 'Paschim Vihar', 'Paschim Vihar', 15, 'Shakur Basti', 'Chandni Chowk', 'North', 'Keshav Puram', 'GEN'),
(60, 'Rani Bagh', 'Rani Bagh (W)', 15, 'Shakur Basti', 'Chandni Chowk', 'North', 'Keshav Puram', 'WOMEN'),
(61, 'Kohat Enclave', 'Kohat Enclave', 15, 'Shakur Basti', 'Chandni Chowk', 'North', 'Keshav Puram', 'GEN'),
(62, 'Shakur Pur', 'Shakur Pur (SC)', 16, 'Tri Nagar', 'Chandni Chowk', 'North', 'Keshav Puram', 'SC'),
(63, 'Tri Nagar', 'Tri Nagar (W)', 16, 'Tri Nagar', 'Chandni Chowk', 'North', 'Keshav Puram', 'WOMEN'),
(64, 'Keshav Puram', 'Keshav Puram', 16, 'Tri Nagar', 'Chandni Chowk', 'North', 'Keshav Puram', 'GEN'),
(65, 'Ashok Vihar', 'Ashok Vihar (W)', 17, 'Wazirpur', 'Chandni Chowk', 'North', 'Keshav Puram', 'WOMEN'),
(66, 'Wazir Pur', 'Wazir Pur (SC-W)', 17, 'Wazirpur', 'Chandni Chowk', 'North', 'Keshav Puram', 'SC_WOMEN'),
(67, 'Sangam Park', 'Sangam Park (SC)', 18, 'Model Town', 'Chandni Chowk', 'North', 'Civil Lines', 'SC'),
(68, 'Model Town', 'Model Town', 18, 'Model Town', 'Chandni Chowk', 'North', 'Civil Lines', 'GEN'),
(69, 'Kamla Nagar', 'Kamla Nagar (W)', 18, 'Model Town', 'Chandni Chowk', 'North', 'Civil Lines', 'WOMEN'),
(70, 'Shastri Nagar', 'Shastri Nagar', 19, 'Sadar Bazar', 'Chandni Chowk', 'Central', 'City SP', 'GEN'),
(71, 'Kishan Ganj', 'Kishan Ganj (SC-W)', 19, 'Sadar Bazar', 'Chandni Chowk', 'Central', 'City SP', 'SC_WOMEN'),
(72, 'Sadar Bazar', 'Sadar Bazar (W)', 19, 'Sadar Bazar', 'Chandni Chowk', 'Central', 'City SP', 'WOMEN'),
(73, 'Civil Lines', 'Civil Lines (SC)', 19, 'Sadar Bazar', 'Chandni Chowk', 'Central', 'City SP', 'SC'),
(74, 'Chandni Chowk', 'Chandni Chowk', 20, 'Chandni Chowk', 'Chandni Chowk', 'Central', 'City SP', 'GEN'),
(75, 'Jama Masjid', 'Jama Masjid (W)', 20, 'Chandni Chowk', 'Chandni Chowk', 'Central', 'City SP', 'WOMEN'),
(76, 'Chandani Mahal', 'Chandani Mahal', 20, 'Chandni Chowk', 'Chandni Chowk', 'Central', 'City SP', 'GEN'),
(77, 'Delhi Gate', 'Delhi Gate (SC-W)', 21, 'Matia Mahal', 'Chandni Chowk', 'Central', 'City SP', 'SC_WOMEN'),
(78, 'Bazar Sita Ram', 'Bazar Sita Ram (W)', 21, 'Matia Mahal', 'Chandni Chowk', 'Central', 'City SP', 'WOMEN'),
(79, 'Ballimaran', 'Ballimaran', 22, 'Ballimaran', 'Chandni Chowk', 'Central', 'City SP', 'GEN'),
(80, 'Ram Nagar', 'Ram Nagar (SC)', 22, 'Ballimaran', 'Chandni Chowk', 'Central', 'City SP', 'SC'),
(81, 'Quraish Nagar', 'Quraish Nagar (W)', 22, 'Ballimaran', 'Chandni Chowk', 'Central', 'City SP', 'WOMEN'),
(82, 'Pahar Ganj', 'Pahar Ganj', 23, 'Karol Bagh', 'New Delhi', 'Central', 'Karol Bagh', 'GEN'),
(83, 'Karol Bagh', 'Karol Bagh (SC-W)', 23, 'Karol Bagh', 'New Delhi', 'Central', 'Karol Bagh', 'SC_WOMEN'),
(84, 'Dev Nagar', 'Dev Nagar (SC)', 23, 'Karol Bagh', 'New Delhi', 'Central', 'Karol Bagh', 'SC'),
(85, 'West Patel Nagar', 'West Patel Nagar (SC-W)', 24, 'Patel Nagar', 'New Delhi', 'Central', 'Karol Bagh', 'SC_WOMEN'),
(86, 'East Patel Nagar', 'East Patel Nagar (W)', 24, 'Patel Nagar', 'New Delhi', 'Central', 'Karol Bagh', 'WOMEN'),
(87, 'Ranjeet Nagar', 'Ranjeet Nagar', 24, 'Patel Nagar', 'New Delhi', 'Central', 'Karol Bagh', 'GEN'),
(88, 'Baljeet Nagar', 'Baljeet Nagar (W)', 24, 'Patel Nagar', 'New Delhi', 'Central', 'Karol Bagh', 'WOMEN'),
(89, 'Karam Pura', 'Karam Pura', 25, 'Moti Nagar', 'New Delhi', 'West', 'Karol Bagh', 'GEN'),
(90, 'Moti Nagar', 'Moti Nagar (W)', 25, 'Moti Nagar', 'New Delhi', 'West', 'Karol Bagh', 'WOMEN'),
(91, 'Ramesh Nagar', 'Ramesh Nagar', 25, 'Moti Nagar', 'New Delhi', 'West', 'Karol Bagh', 'GEN'),
(92, 'Punjabi Bagh', 'Punjabi Bagh (W)', 25, 'Moti Nagar', 'New Delhi', 'West', 'Karol Bagh', 'WOMEN'),
(93, 'Madipur', 'Madipur (SC)', 26, 'Madipur', 'West Delhi', 'West', 'West', 'SC'),
(94, 'Raghubir Nagar', 'Raghubir Nagar (SC-W)', 26, 'Madipur', 'West Delhi', 'West', 'West', 'SC_WOMEN'),
(95, 'Vishnu Garden', 'Vishnu Garden', 26, 'Madipur', 'West Delhi', 'West', 'West', 'GEN'),
(96, 'Rajouri Garden', 'Rajouri Garden (W)', 27, 'Rajouri Garden', 'West Delhi', 'West', 'West', 'WOMEN'),
(97, 'Chaukhandi Nagar', 'Chaukhandi Nagar', 27, 'Rajouri Garden', 'West Delhi', 'West', 'West', 'GEN'),
(98, 'Subhash Nagar', 'Subhash Nagar (W)', 27, 'Rajouri Garden', 'West Delhi', 'West', 'West', 'WOMEN'),
(99, 'Hari Nagar', 'Hari Nagar', 28, 'Hari Nagar', 'West Delhi', 'West', 'West', 'GEN'),
(100, 'Fateh Nagar', 'Fateh Nagar (W)', 28, 'Hari Nagar', 'West Delhi', 'West', 'West', 'WOMEN'),
(101, 'Tilak Nagar', 'Tilak Nagar', 28, 'Hari Nagar', 'West Delhi', 'West', 'West', 'GEN'),
(102, 'Khyala', 'Khyala (W)', 28, 'Hari Nagar', 'West Delhi', 'West', 'West', 'WOMEN'),
(103, 'Keshopur', 'Keshopur', 29, 'Tilak Nagar', 'West Delhi', 'West', 'West', 'GEN'),
(104, 'Janak Puri South', 'Janak Puri South (W)', 29, 'Tilak Nagar', 'West Delhi', 'West', 'West', 'WOMEN'),
(105, 'Mahaveer Enclave', 'Mahaveer Enclave', 29, 'Tilak Nagar', 'West Delhi', 'West', 'West', 'GEN'),
(106, 'Janak Puri West', 'Janak Puri West (W)', 30, 'Janakpuri', 'West Delhi', 'West', 'West', 'WOMEN'),
(107, 'Vikas Puri', 'Vikas Puri', 30, 'Janakpuri', 'West Delhi', 'West', 'West', 'GEN'),
(108, 'Hastsal', 'Hastsal (W)', 30, 'Janakpuri', 'West Delhi', 'West', 'West', 'WOMEN'),
(109, 'Shiv Vihar', 'Shiv Vihar', 31, 'Vikas Puri', 'West Delhi', 'West', 'West', 'GEN'),
(110, 'Bhakkar Wala', 'Bhakkar Wala (W)', 31, 'Vikas Puri', 'West Delhi', 'West', 'West', 'WOMEN'),
(111, 'Baprola', 'Baprola', 31, 'Vikas Puri', 'West Delhi', 'West', 'West', 'GEN'),
(112, 'Vikas Nagar', 'Vikas Nagar (W)', 31, 'Vikas Puri', 'West Delhi', 'West', 'West', 'WOMEN'),
(113, 'Mohan Garden-West', 'Mohan Garden-West', 31, 'Vikas Puri', 'West Delhi', 'West', 'West', 'GEN'),
(114, 'Mohan Garden-East', 'Mohan Garden-East (W)', 31, 'Vikas Puri', 'West Delhi', 'West', 'West', 'WOMEN'),
(115, 'Uttam Nagar', 'Uttam Nagar', 32, 'Uttam Nagar', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(116, 'Binda Pur', 'Binda Pur (W)', 32, 'Uttam Nagar', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(117, 'Dabri', 'Dabri', 32, 'Uttam Nagar', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(118, 'Sagarpur', 'Sagarpur (W)', 33, 'Dwarka', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(119, 'Manglapuri', 'Manglapuri', 33, 'Dwarka', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(120, 'Dwarka-B', 'Dwarka-B (W)', 33, 'Dwarka', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(121, 'Dwarka-A', 'Dwarka-A', 34, 'Matiala', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(122, 'Matiala', 'Matiala (W)', 34, 'Matiala', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(123, 'Kakrola', 'Kakrola', 34, 'Matiala', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(124, 'Nangli Sakrawati', 'Nangli Sakrawati (W)', 34, 'Matiala', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(125, 'Chhawala', 'Chhawala', 35, 'Najafgarh', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(126, 'Isapur', 'Isapur (W)', 35, 'Najafgarh', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(127, 'Najafgarh', 'Najafgarh', 35, 'Najafgarh', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(128, 'Dichaon Kalan', 'Dichaon Kalan (W)', 35, 'Najafgarh', 'West Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(129, 'Roshan Pura', 'Roshan Pura', 35, 'Najafgarh', 'West Delhi', 'South West', 'Najafgarh', 'GEN'),
(130, 'Dwarka-C', 'Dwarka-C (W)', 36, 'Bijwasan', 'South Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(131, 'Bijwasan', 'Bijwasan', 36, 'Bijwasan', 'South Delhi', 'South West', 'Najafgarh', 'GEN'),
(132, 'Kapashera', 'Kapashera (W)', 36, 'Bijwasan', 'South Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(133, 'Mahipalpur', 'Mahipalpur', 36, 'Bijwasan', 'South Delhi', 'South West', 'Najafgarh', 'GEN'),
(134, 'Raj Nagar', 'Raj Nagar (W)', 37, 'Palam', 'South Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(135, 'Palam', 'Palam', 37, 'Palam', 'South Delhi', 'South West', 'Najafgarh', 'GEN'),
(136, 'Madhu Vihar', 'Madhu Vihar (W)', 37, 'Palam', 'South Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(137, 'Mahavir Enclave', 'Mahavir Enclave', 37, 'Palam', 'South Delhi', 'South West', 'Najafgarh', 'GEN'),
(138, 'Sadh Nagar', 'Sadh Nagar (W)', 37, 'Palam', 'South Delhi', 'South West', 'Najafgarh', 'WOMEN'),
(139, 'Naraina', 'Naraina', 39, 'Rajinder Nagar', 'New Delhi', 'New Delhi', 'Karol Bagh', 'GEN'),
(140, 'Inder Puri', 'Inder Puri (SC)', 39, 'Rajinder Nagar', 'New Delhi', 'New Delhi', 'Karol Bagh', 'SC'),
(141, 'Rajinder Nagar', 'Rajinder Nagar (W)', 39, 'Rajinder Nagar', 'New Delhi', 'New Delhi', 'Karol Bagh', 'WOMEN'),
(142, 'Daryaganj', 'Daryaganj', 41, 'Jangpura', 'East Delhi', 'South East', 'Central', 'GEN'),
(143, 'Sidhartha Nagar', 'Sidhartha Nagar (W)', 41, 'Jangpura', 'East Delhi', 'South East', 'Central', 'WOMEN'),
(144, 'Lajpat Nagar', 'Lajpat Nagar', 41, 'Jangpura', 'East Delhi', 'South East', 'Central', 'GEN'),
(145, 'Andrews Ganj', 'Andrews Ganj (W)', 42, 'Kasturba Nagar', 'New Delhi', 'South', 'Central', 'WOMEN'),
(146, 'Amar Colony', 'Amar Colony', 42, 'Kasturba Nagar', 'New Delhi', 'South', 'Central', 'GEN'),
(147, 'Kotla Mubarakpur', 'Kotla Mubarakpur (W)', 42, 'Kasturba Nagar', 'New Delhi', 'South', 'Central', 'WOMEN'),
(148, 'Hauz Khas', 'Hauz Khas', 43, 'Malviya Nagar', 'New Delhi', 'South', 'South', 'GEN'),
(149, 'Malviya Nagar', 'Malviya Nagar (W)', 43, 'Malviya Nagar', 'New Delhi', 'South', 'South', 'WOMEN'),
(150, 'Green Park', 'Green Park', 43, 'Malviya Nagar', 'New Delhi', 'South', 'South', 'GEN'),
(151, 'Munirka', 'Munirka (W)', 44, 'R.K. Puram', 'New Delhi', 'New Delhi', 'South', 'WOMEN'),
(152, 'R.K Puram', 'R.K Puram', 44, 'R.K. Puram', 'New Delhi', 'New Delhi', 'South', 'GEN'),
(153, 'Vasant Vihar', 'Vasant Vihar (W)', 44, 'R.K. Puram', 'New Delhi', 'New Delhi', 'South', 'WOMEN'),
(154, 'Lado Sarai', 'Lado Sarai', 45, 'Mehrauli', 'South Delhi', 'South', 'South', 'GEN'),
(155, 'Mehrauli', 'Mehrauli (W)', 45, 'Mehrauli', 'South Delhi', 'South', 'South', 'WOMEN'),
(156, 'Vasant Kunj', 'Vasant Kunj', 45, 'Mehrauli', 'South Delhi', 'South', 'South', 'GEN'),
(157, 'Aya Nagar', 'Aya Nagar (W)', 46, 'Chhatarpur', 'South Delhi', 'South', 'South', 'WOMEN'),
(158, 'Bhati', 'Bhati', 46, 'Chhatarpur', 'South Delhi', 'South', 'South', 'GEN'),
(159, 'Chhatarpur', 'Chhatarpur (W)', 46, 'Chhatarpur', 'South Delhi', 'South', 'South', 'WOMEN'),
(160, 'Said-Ul-Ajaib', 'Said-Ul-Ajaib', 47, 'Deoli', 'South Delhi', 'South', 'South', 'GEN'),
(161, 'Deoli', 'Deoli (W)', 47, 'Deoli', 'South Delhi', 'South', 'South', 'WOMEN'),
(162, 'Tigri', 'Tigri (SC-W)', 47, 'Deoli', 'South Delhi', 'South', 'South', 'SC_WOMEN'),
(163, 'Sangam Vihar-A', 'Sangam Vihar-A', 47, 'Deoli', 'South Delhi', 'South', 'South', 'GEN'),
(164, 'Dakshin Puri', 'Dakshin Puri (SC)', 48, 'Ambedkar Nagar', 'South Delhi', 'South', 'South', 'SC'),
(165, 'Madangir', 'Madangir (SC-W)', 48, 'Ambedkar Nagar', 'South Delhi', 'South', 'South', 'SC_WOMEN'),
(166, 'Pushp Vihar', 'Pushp Vihar (SC)', 48, 'Ambedkar Nagar', 'South Delhi', 'South', 'South', 'SC'),
(167, 'Khanpur', 'Khanpur (W)', 49, 'Sangam Vihar', 'South Delhi', 'South', 'South', 'WOMEN'),
(168, 'Sangam Vihar-C', 'Sangam Vihar-C', 49, 'Sangam Vihar', 'South Delhi', 'South', 'South', 'GEN'),
(169, 'Sangam Vihar-B', 'Sangam Vihar-B (W)', 49, 'Sangam Vihar', 'South Delhi', 'South', 'South', 'WOMEN'),
(170, 'Tughlakabad Extension', 'Tughlakabad Extension', 50, 'Greater Kailash', 'New Delhi', 'South', 'Central', 'GEN'),
(171, 'Chitaranjan Park', 'Chitaranjan Park (W)', 50, 'Greater Kailash', 'New Delhi', 'South', 'Central', 'WOMEN'),
(172, 'Chirag Delhi', 'Chirag Delhi', 50, 'Greater Kailash', 'New Delhi', 'South', 'Central', 'GEN'),
(173, 'Greater Kailash', 'Greater Kailash (W)', 50, 'Greater Kailash', 'New Delhi', 'South', 'Central', 'WOMEN'),
(174, 'Sri Niwas Puri', 'Sri Niwas Puri', 51, 'Kalkaji', 'South Delhi', 'South East', 'Central', 'GEN'),
(175, 'Kalkaji', 'Kalkaji (W)', 51, 'Kalkaji', 'South Delhi', 'South East', 'Central', 'WOMEN'),
(176, 'Govind Puri', 'Govind Puri', 51, 'Kalkaji', 'South Delhi', 'South East', 'Central', 'GEN'),
(177, 'Harkesh Nagar', 'Harkesh Nagar (SC-W)', 52, 'Tughlakabad', 'South Delhi', 'South East', 'Central', 'SC_WOMEN'),
(178, 'Tughlakabad', 'Tughlakabad (W)', 52, 'Tughlakabad', 'South Delhi', 'South East', 'Central', 'WOMEN'),
(179, 'Pul Pehladpur', 'Pul Pehladpur (SC)', 53, 'Badarpur', 'South Delhi', 'South East', 'Central', 'SC'),
(180, 'Badarpur', 'Badarpur (SC-W)', 53, 'Badarpur', 'South Delhi', 'South East', 'Central', 'SC_WOMEN'),
(181, 'Molarband', 'Molarband', 53, 'Badarpur', 'South Delhi', 'South East', 'Central', 'GEN'),
(182, 'Meethapur', 'Meethapur (W)', 53, 'Badarpur', 'South Delhi', 'South East', 'Central', 'WOMEN'),
(183, 'Hari Nagar Extension', 'Hari Nagar Extension', 53, 'Badarpur', 'South Delhi', 'South East', 'Central', 'GEN'),
(184, 'Jaitpur', 'Jaitpur (W)', 54, 'Okhla', 'East Delhi', 'South East', 'Central', 'WOMEN'),
(185, 'Madanpur Khadar East', 'Madanpur Khadar East (SC)', 54, 'Okhla', 'East Delhi', 'South East', 'Central', 'SC'),
(186, 'Madanpur Khadar West', 'Madanpur Khadar West', 54, 'Okhla', 'East Delhi', 'South East', 'Central', 'GEN'),
(187, 'Sarita Vihar', 'Sarita Vihar (W)', 54, 'Okhla', 'East Delhi', 'South East', 'Central', 'WOMEN'),
(188, 'Abul Fazal Enclave', 'Abul Fazal Enclave', 54, 'Okhla', 'East Delhi', 'South East', 'Central', 'GEN'),
(189, 'Zakir Nagar', 'Zakir Nagar (W)', 54, 'Okhla', 'East Delhi', 'South East', 'Central', 'WOMEN'),
(190, 'New Ashok Nagar', 'New Ashok Nagar', 55, 'Trilokpuri', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(191, 'Mayur Vihar Phase-I', 'Mayur Vihar Phase-I (SC-W)', 55, 'Trilokpuri', 'East Delhi', 'East', 'Shahdara South', 'SC_WOMEN'),
(192, 'Trilokpuri', 'Trilokpuri (SC)', 55, 'Trilokpuri', 'East Delhi', 'East', 'Shahdara South', 'SC'),
(193, 'Kondli', 'Kondli (W)', 56, 'Kondli', 'East Delhi', 'East', 'Shahdara South', 'WOMEN'),
(194, 'Gharoli', 'Gharoli (SC-W)', 56, 'Kondli', 'East Delhi', 'East', 'Shahdara South', 'SC_WOMEN'),
(195, 'Kalyanpuri', 'Kalyanpuri (SC)', 56, 'Kondli', 'East Delhi', 'East', 'Shahdara South', 'SC'),
(196, 'Mayur Vihar Phase-II', 'Mayur Vihar Phase-II', 57, 'Patparganj', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(197, 'Patpar Ganj', 'Patpar Ganj (SC)', 57, 'Patparganj', 'East Delhi', 'East', 'Shahdara South', 'SC'),
(198, 'Vinod Nagar', 'Vinod Nagar', 57, 'Patparganj', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(199, 'Mandawali', 'Mandawali (SC)', 57, 'Patparganj', 'East Delhi', 'East', 'Shahdara South', 'SC'),
(200, 'Pandav Nagar', 'Pandav Nagar', 58, 'Laxmi Nagar', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(201, 'Lalita Park', 'Lalita Park (W)', 58, 'Laxmi Nagar', 'East Delhi', 'East', 'Shahdara South', 'WOMEN'),
(202, 'Shakarpur', 'Shakarpur', 58, 'Laxmi Nagar', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(203, 'Laxmi Nagar', 'Laxmi Nagar (SC)', 58, 'Laxmi Nagar', 'East Delhi', 'East', 'Shahdara South', 'SC'),
(204, 'Preet Vihar', 'Preet Vihar', 59, 'Vishwas Nagar', 'East Delhi', 'Shahdara', 'Shahdara South', 'GEN'),
(205, 'I.P Extension', 'I.P Extension (SC)', 59, 'Vishwas Nagar', 'East Delhi', 'Shahdara', 'Shahdara South', 'SC'),
(206, 'Anand Vihar', 'Anand Vihar', 59, 'Vishwas Nagar', 'East Delhi', 'Shahdara', 'Shahdara South', 'GEN'),
(207, 'Vishwas Nagar', 'Vishwas Nagar (SC-W)', 59, 'Vishwas Nagar', 'East Delhi', 'Shahdara', 'Shahdara South', 'SC_WOMEN'),
(208, 'Anarkali', 'Anarkali (W)', 60, 'Krishna Nagar', 'East Delhi', 'East', 'Shahdara South', 'WOMEN'),
(209, 'Jagat Puri', 'Jagat Puri', 60, 'Krishna Nagar', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(210, 'Geeta Colony', 'Geeta Colony (W)', 60, 'Krishna Nagar', 'East Delhi', 'East', 'Shahdara South', 'WOMEN'),
(211, 'Krishna Nagar', 'Krishna Nagar', 60, 'Krishna Nagar', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(212, 'Gandhi Nagar', 'Gandhi Nagar (W)', 61, 'Gandhi Nagar', 'East Delhi', 'East', 'Shahdara South', 'WOMEN'),
(213, 'Shastri Park', 'Shastri Park', 61, 'Gandhi Nagar', 'East Delhi', 'East', 'Shahdara South', 'GEN'),
(214, 'Azad Nagar', 'Azad Nagar (W)', 61, 'Gandhi Nagar', 'East Delhi', 'East', 'Shahdara South', 'WOMEN'),
(215, 'Shahdara', 'Shahdara (SC)', 62, 'Shahdara', 'East Delhi', 'Shahdara', 'Shahdara North', 'SC'),
(216, 'Jhilmil', 'Jhilmil', 62, 'Shahdara', 'East Delhi', 'Shahdara', 'Shahdara North', 'GEN'),
(217, 'Dilshad Colony', 'Dilshad Colony (W)', 62, 'Shahdara', 'East Delhi', 'Shahdara', 'Shahdara North', 'WOMEN'),
(218, 'Sundar Nagri', 'Sundar Nagri (SC-W)', 63, 'Seemapuri', 'North East Delhi', 'Shahdara', 'Shahdara North', 'SC_WOMEN'),
(219, 'Dilshad Garden', 'Dilshad Garden', 63, 'Seemapuri', 'North East Delhi', 'Shahdara', 'Shahdara North', 'GEN'),
(220, 'Nand Nagri', 'Nand Nagri (SC)', 63, 'Seemapuri', 'North East Delhi', 'Shahdara', 'Shahdara North', 'SC'),
(221, 'Ashok Nagar', 'Ashok Nagar (W)', 63, 'Seemapuri', 'North East Delhi', 'Shahdara', 'Shahdara North', 'WOMEN'),
(222, 'Ram Nagar East', 'Ram Nagar East', 64, 'Rohtas Nagar', 'North East Delhi', 'Shahdara', 'Shahdara North', 'GEN'),
(223, 'Rohtash Nagar', 'Rohtash Nagar (W)', 64, 'Rohtas Nagar', 'North East Delhi', 'Shahdara', 'Shahdara North', 'WOMEN'),
(224, 'Welcome Colony', 'Welcome Colony', 64, 'Rohtas Nagar', 'North East Delhi', 'Shahdara', 'Shahdara North', 'GEN'),
(225, 'Seelampur', 'Seelampur (W)', 65, 'Seelampur', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(226, 'Gautam Puri', 'Gautam Puri', 65, 'Seelampur', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(227, 'Chauhan Banger', 'Chauhan Banger (W)', 65, 'Seelampur', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(228, 'Maujpur', 'Maujpur', 65, 'Seelampur', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(229, 'Braham Puri', 'Braham Puri (W)', 66, 'Ghonda', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(230, 'Bhajanpura', 'Bhajanpura', 66, 'Ghonda', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(231, 'Ghonda', 'Ghonda (W)', 66, 'Ghonda', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(232, 'Yamuna Vihar', 'Yamuna Vihar', 66, 'Ghonda', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(233, 'Subash Mohalla', 'Subash Mohalla (W)', 67, 'Babarpur', 'North East Delhi', 'Shahdara', 'Shahdara North', 'WOMEN'),
(234, 'Kabir Nagar', 'Kabir Nagar', 67, 'Babarpur', 'North East Delhi', 'Shahdara', 'Shahdara North', 'GEN'),
(235, 'Gorakh Park', 'Gorakh Park (W)', 67, 'Babarpur', 'North East Delhi', 'Shahdara', 'Shahdara North', 'WOMEN'),
(236, 'Kardam Puri', 'Kardam Puri', 67, 'Babarpur', 'North East Delhi', 'Shahdara', 'Shahdara North', 'GEN'),
(237, 'Harsh Vihar', 'Harsh Vihar (SC-W)', 68, 'Gokalpur', 'North East Delhi', 'North East', 'Shahdara North', 'SC_WOMEN'),
(238, 'Saboli', 'Saboli (SC)', 68, 'Gokalpur', 'North East Delhi', 'North East', 'Shahdara North', 'SC'),
(239, 'Gokal Puri', 'Gokal Puri (SC-W)', 68, 'Gokalpur', 'North East Delhi', 'North East', 'Shahdara North', 'SC_WOMEN'),
(240, 'Joharipur', 'Joharipur (SC)', 68, 'Gokalpur', 'North East Delhi', 'North East', 'Shahdara North', 'SC'),
(241, 'Karawal Nagar-East', 'Karawal Nagar-East (W)', 69, 'Mustafabad', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(242, 'Dayalpur', 'Dayalpur', 69, 'Mustafabad', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(243, 'Mustafabad', 'Mustafabad (W)', 69, 'Mustafabad', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(244, 'Nehru Vihar', 'Nehru Vihar', 69, 'Mustafabad', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(245, 'Brij Puri', 'Brij Puri (W)', 69, 'Mustafabad', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(246, 'Sri Ram Colony', 'Sri Ram Colony', 70, 'Karawal Nagar', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(247, 'Sadatpur', 'Sadatpur (W)', 70, 'Karawal Nagar', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(248, 'Karawal Nagar-West', 'Karawal Nagar-West', 70, 'Karawal Nagar', 'North East Delhi', 'North East', 'Shahdara North', 'GEN'),
(249, 'Sonia Vihar', 'Sonia Vihar (W)', 70, 'Karawal Nagar', 'North East Delhi', 'North East', 'Shahdara North', 'WOMEN'),
(250, 'Sabapur', 'Sabapur', 70, 'Karawal Nagar', 'North East Delhi', 'North East', 'Shahdara North', 'GEN')
ON CONFLICT (ward_number) DO UPDATE SET
    name = EXCLUDED.name,
    raw_name = EXCLUDED.raw_name,
    ac_number = EXCLUDED.ac_number,
    ac_name = EXCLUDED.ac_name,
    lok_sabha = EXCLUDED.lok_sabha,
    district = EXCLUDED.district,
    zone = EXCLUDED.zone,
    reservation = EXCLUDED.reservation;
